name: 🐛 Bug Report
description: Create a report to help us improve
title: "[BUG] "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        
  - type: checkboxes
    attributes:
      label: Prerequisites
      options:
        - label: I have checked that this issue has not already been reported
          required: true
        - label: I have updated to the latest version
          required: true

  - type: input
    attributes:
      label: BozoCord Version
      description: What version of BozoCord are you running?
      placeholder: v1.0.0
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Environment
      options:
        - Production
        - Development
        - Testing
    validations:
      required: true

  - type: textarea
    attributes:
      label: Current Behavior
      description: A clear description of what the bug is
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected Behavior
      description: What you expected to happen
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    attributes:
      label: Error Logs
      description: Paste any relevant error logs here
      render: shell

  - type: textarea
    attributes:
      label: Additional Context
      description: Add any other context about the problem here 